name: Sync labels
on:
  push:
    branches:
    - main

jobs:
  build:
    timeout-minutes: 5
    permissions:
      contents: read
      issues: write # https://github.com/orgs/community/discussions/13565
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync labels
        uses: tapihdev/actionshub/micnncim/action-label-syncer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
