name: Tagpr
on:
  push:
    branches:
    - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tagpr
        id: tagpr
        uses: tapihdev/actionshub/Songmu/tagpr@main

      - name: Annotate major and minor tags
        if: steps.tagpr.outputs.tag != ''
        uses: ./
        with:
          tag: ${{ steps.tagpr.outputs.tag }}
